spring:
  application:
    name: IPiece
  profiles:
    active: local


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  data:
    redis:
      host: 192.168.0.122
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true  # (Spring Boot 3.1+) SQL 색상 강조
    show-sql: true        # SQL 쿼리 출력


server:
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: never

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000          # AccessToken 1시간
  refresh-expiration-ms: 604800000 # RefreshToken 7일


  solapi:
    api-key: ${SOLAPI_API_KEY}
    api-secret: ${SOLAPI_API_SECRET}
    sender: ${SOLAPI_SENDER}




